### ISSUE TITLE
When will it be released?

### ISSUE THREAD

**Issue by zza1617** [koide3/direct_visual_lidar_calibration#1]

**Comment by koide3** [comment]
Maybe in late March or April. I'm fully occupied with preparing a paper for IROS2023 and some other works for now.

**Comment by zza1617** [comment]
Sorry to bother you again, but when can you release the code，Thanks again for your work.

**Comment by zza1617** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月29日(星期三) 中午11:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [koide3/direct_visual_lidar_calibration] When will it be released? (Issue #1)





 
Maybe it will get released in one week.
 Although it still needs a bit tweaking of UI, it's almost ready. The documentation is already made available online, and you can try it if you need.
