### ISSUE TITLE
Ubuntu20.04 ROS1 Noetic run error

### ISSUE THREAD

**Issue by WeiZixu-HIT** [koide3/direct_visual_lidar_calibration#105]
rosrun direct_visual_lidar_calibration preprocess /home/icebear/下载/livox_ros1 livox_preprocessed -av
data_path: /home/icebear/下载/livox_ros1
dst_path : livox_preprocessed
input_bags:
- /home/icebear/下载/livox_ros1/rosbag2_2023_03_09-13_44_54.bag
- /home/icebear/下载/livox_ros1/rosbag2_2023_03_09-13_42_46.bag
- /home/icebear/下载/livox_ros1/rosbag2_2023_03_09-13_46_54.bag
- /home/icebear/下载/livox_ros1/rosbag2_2023_03_09-13_44_10.bag
- /home/icebear/下载/livox_ros1/rosbag2_2023_03_09-13_46_10.bag
topics in /home/icebear/下载/livox_ros1/rosbag2_2023_03_09-13_42_46.bag:
- /livox/points : sensor_msgs/PointCloud2
- /livox/imu : sensor_msgs/Imu
- /image : sensor_msgs/Image
- /camera_info : sensor_msgs/CameraInfo
selected topics:
- camera_info: /camera_info
- image      : /image
- points     : /livox/points
intensity_channel: intensity
try to get the camera model automatically
warning: bag does not contain topic
       : bag_filename=/home/icebear/下载/livox_ros1/rosbag2_2023_03_09-13_42_46.bag
       : topic=/camera_info
段错误 (核心已转储)

**Comment by leoxiang66** [comment]
Hi I've met the same problem. Did you solve it?
