### ISSUE TITLE
Preprocessing bag point cloud does not perform dense point cloud reconstruction

### ISSUE THREAD

**Issue by oulton** [koide3/direct_visual_lidar_calibration#106]
docker run \
  -it \
  --rm \
  --net host \
  --gpus all \
  -e DISPLAY=$DISPLAY \
  -v $HOME/.Xauthority:/root/.Xauthority \
  -v $bag_path:/tmp/input_bags \
  -v $preprocessed_path:/tmp/preprocessed \
  koide3/direct_visual_lidar_calibration:noetic \
  rosrun direct_visual_lidar_calibration preprocess -av \
  --camera_model plumb_bob \
  --camera_intrinsic 793.12038,793.39645,642.28865,339.063046 \
  --camera_distortion_coeffs -0.35688425,0.1004065,-0.00069925,0.000116,0 \
  /tmp/input_bags /tmp/preprocessed

when i run preprocess node with a bag, and the car is moving.
This preprocess node can  perform dense point cloud reconstruction, but in docker i can not get the reconstruction cloud,it just a simple overlay of many frames.

**Comment by koide3** [comment]
You need to add `-d` option to enable the dynamic point integrator.
