### ISSUE TITLE
I find a bug when using find_matches_superglue.py

### ISSUE THREAD

**Issue by Jeasonlee313** [koide3/direct_visual_lidar_calibration#12]
I think the bug might be caused for the version of matplotlib
When I was using find_matches_superglue.py to automatic initial guess, there raises a ValueError: "Colormap turbo is not recognized. Possible values are: Accent, Accent_r, blabla..." in line 136 in direct_visual_lidar_calibration/scripts/find_matches_superglue.py.
I use matplotlib 3.1.2, could you like to give me your matplotlib version to check the bug can be solved or not?

**Comment by koide3** [comment]
```
$ pip show matplotlib
Name: matplotlib
Version: 3.5.1
```

**Comment by Jeasonlee313** [comment]
> ```
> $ pip show matplotlib
> Name: matplotlib
> Version: 3.5.1
> ```

Thank you! I can use find_matches_superglue.py to auto initial guess, but there are still some misalignment between camera and Lidar in the test data livox

**Comment by Jeasonlee313** [comment]
![uTools_1682592226591](https://user-images.githubusercontent.com/52118576/234840017-abdcfafd-dea6-46bf-a5b6-43c34cde459a.png)

**Comment by Jeasonlee313** [comment]
> > ```
> > $ pip show matplotlib
> > Name: matplotlib
> > Version: 3.5.1
> > ```
> 
> Thank you! I can use find_matches_superglue.py to auto initial guess, but there are still some misalignment between camera and Lidar in the test data livox

I'm sorry, I input wrong intrinsic parameters, and now I can get the correct results. I will close this issue. Thanks for your help a lot!

**Comment by Jeasonlee313** [comment]
![uTools_1682593888779](https://user-images.githubusercontent.com/52118576/234845844-7d01e52c-2c2e-428c-ac3e-37056bc9361b.png)
