### ISSUE TITLE
ubuntu20.04  arm  catkin_make error  

### ISSUE THREAD

**Issue by keepermzw** [koide3/direct_visual_lidar_calibration#120]
CMake Error at /usr/local/lib/cmake/iridescence/iridescence-config.cmake:43 (add_library):
  add_library cannot create ALIAS target "Iridescence::Iridescence" because
  target "Iridescence::iridescence" is imported but not globally visible.

How to solve this quetsion?please

**Comment by santu97** [comment]
I also encountered this, have you solved it?

**Comment by santu97** [comment]
I have solved it ：
in /usr/local/lib/cmake/iridescence/iridescence-targets.cmake
modify：add_library(Iridescence::iridescence SHARED IMPORTED) -> add_library(Iridescence::iridescence SHARED IMPORTED GLOBAL)

**Comment by keepermzw** [comment]
> cmake

I have solved it with your advice,thanks

**Comment by keepermzw** [comment]
> I have solved it ： in /usr/local/lib/cmake/iridescence/iridescence-targets.cmake modify：add_library(Iridescence::iridescence SHARED IMPORTED) -> add_library(Iridescence::iridescence SHARED IMPORTED GLOBAL)

I have solved it with your advice,thanks
