### ISSUE TITLE
Throw segmentation fault (core dumped) while processing rosbag from sick lidar

### ISSUE THREAD

**Issue by Seekerzero** [koide3/direct_visual_lidar_calibration#125]
Hi @koide3 , 

I was trying to calibrate a Realsense d435i with a sick multiscan 16 lidar using your calibration.
It throws a segmentation fault (core dumped) while running the preprocess step.

I've checked the program was working on the other data (e.g., rosbag from Livox lidar), so it should be a specific problem for the sick lidar, not from the dependency. I tried to debug the problem and found out it happpend between the [loop](https://github.com/koide3/direct_visual_lidar_calibration/blob/e110ca230e9e262a93d7b2f90c2d498dbc970e71/src/vlcal/preprocess/preprocess.cpp#L443), but not be able to nail it down further since it was randomly stopped between the lines. 

The error is the following
preprocess: /home/zwhy/slam_project/direct_calib/src/direct_visual_lidar_calibration/src/vlcal/common/frame_cpu.cpp:128: void vlcal::FrameCPU::add_intensities(const T*, int) [with T = double]: Assertion `num_points == size()' failed.
Aborted (core dumped)

Is it because the intensity values of the sick lidar points are stored in float32?

I've uploaded an example rosbag [here](https://storagex.seekerzero.science/s/z8uX).
And some additional details about the lidar data can be found [here](https://github.com/SICKAG/sick_scan_xd/blob/develop/launch/sick_multiscan.launch). The intensity channel is named under the field "i".

Could you help me out of this and give me some insight?
Thank you so much!

**Comment by Seekerzero** [comment]
Hi Koide, 
I just found out it is caused by a typo in ros_cloud_converter. Please check the pull request.

**Comment by koide3** [comment]
Ah, what a silly mistake I made! Thanks a lot for finding it! I just merged your PR!

**Comment by Seekerzero** [comment]
No problem! My pleasure!
