### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by zza1617** [koide3/direct_visual_lidar_calibration#14]
CMake Error at CppUnitLite/CMakeLists.txt:6 (add_library):
  Target "CppUnitLite" links to target "Boost::boost" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at gtsam/CMakeLists.txt:107 (add_library):
  Target "gtsam" links to target "Boost::serialization" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at gtsam/CMakeLists.txt:107 (add_library):
  Target "gtsam" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at gtsam/CMakeLists.txt:107 (add_library):
  Target "gtsam" links to target "Boost::filesystem" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
how to deal with it?

**Comment by koide3** [comment]
You may need to do `sudo apt install libboost-all-dev`

**Comment by zza1617** [comment]
I think I have installed libboost-all-dev. 
/usr/lib/x86_64-linux-gnu includes boost_ ...

**Comment by koide3** [comment]
Did you get the error during the build of GTSAM?

**Comment by zza1617** [comment]
I have resolved the previous issue by replacing errors like "Boost::boost" with "${Boost_LIBRARY}". The problem has been resolved.

















------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月7日(星期三) 下午2:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [koide3/direct_visual_lidar_calibration] Installation Problem (Issue #14)





 
Did you get the error during the build of GTSAM?

**Comment by zza1617** [comment]
When I Install Iridescence for visualization,
I meet this error: 
/home/zza/iridescence/src/guik/viewer/info_window.cpp:11:10: fatal error: boost/process/child.hpp: No such file or directory
11 | #include <boost/process/child.hpp>
| ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
How to resolve this issue?
look forward to your reply.
thanks

**Comment by zza1617** [comment]
My system is ubuntu16.04, boost1.58 @koide3

**Comment by koide3** [comment]
Sorry, we do not support environments older than Ubuntu 20.04. But you can still use this package without installation by using docker images.

**Comment by BestVanRome** [comment]
@koide3 your docker-files seems to be missing the  `Iridescence_LIBRARIES`. (Both: noetic and humble).
Got errors on trying to build both.

**Comment by koide3** [comment]
@BestVanRome 
Thanks for reporting. The error should be fixed by https://github.com/koide3/direct_visual_lidar_calibration/pull/96 .

**Comment by BestVanRome** [comment]
> @koide3 your docker-files seems to be missing the `Iridescence_LIBRARIES`. (Both: noetic and humble). Got errors on trying to build both.

@koide3 do you want to update your docker-files as well?

**Comment by koide3** [comment]
@BestVanRome 
No, it's not necessary. The error was fixed by the modification made on FindIridescence.cmake.
