### ISSUE TITLE
Error from using docker environment

### ISSUE THREAD

**Issue by rainlord2** [koide3/direct_visual_lidar_calibration#19]
There is an error when i use docker image,the log fellow this:
glfw error 65544: X11: The DISPLAY environment variable is missing
failed to initialize GLFW

**Comment by koide3** [comment]
Possibly you forgot to add docker options for X11. See [this](https://koide3.github.io/direct_visual_lidar_calibration/docker/).

**Comment by yunzhongxicao** [comment]
i meet the same problem, can you show how to solve it ?

**Comment by xtcl** [comment]
use command `xhost +local:docker` before `docker run`
