### ISSUE TITLE
an error about fmt?

### ISSUE THREAD

**Issue by rainlord2** [koide3/direct_visual_lidar_calibration#20]
In this function of   Eigen::Isometry3d PoseEstimation::estimate_pose_lsq(),the line     "Sophus::SE3d T_camera_lidar = Sophus::SE3d(init_T_camera_lidar.matrix());" has an error of "error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization:"

**Comment by koide3** [comment]
What is your environment? If it's older than Ubuntu 20.04, use the docker images.
