### ISSUE TITLE
 Failed to calibrate the data we collected ourselves 

### ISSUE THREAD

**Issue by Ning030** [koide3/direct_visual_lidar_calibration#24]
lidar: Velodyne 16 line radar
 Registration failed, point cloud registration is chaotic 。

 display warning：

warning: large point timestamp (1687765073.393736 > 1.0) found!!
       : assume that point times are absolute and convert them to relative
       : replace_frame_stamp=1 wrt_first_frame_timestamp=1
warning: use first point timestamp as frame timestamp
       : frame=1687765073.393736 point=1687765073.293307

**Comment by koide3** [comment]
Duplicated https://github.com/koide3/direct_visual_lidar_calibration/issues/13
