### ISSUE TITLE
How to specify camera parameters for preprocessing

### ISSUE THREAD

**Issue by 774880930** [koide3/direct_visual_lidar_calibration#25]
**Before opening an issue**

If the issue is about calibration procedure and results:
- [√] I have read [data collection instructions](https://koide3.github.io/direct_visual_lidar_calibration/collection/)
- [√] I have confirmed [the program works on example data](https://koide3.github.io/direct_visual_lidar_calibration/example/)

**Describe the bug**
I used ROS1. When I was preprocessing, I saw the notes you provided and needed to specify the parameters of the camera in advance, but when I tried to specify the parameters, I got the following results 

![IMG_20230704_193631](https://github.com/koide3/direct_visual_lidar_calibration/assets/109514194/56612a48-8663-4f4c-a264-c55e6bace61d)
![IMG_20230704_193640](https://github.com/koide3/direct_visual_lidar_calibration/assets/109514194/18d3846b-f671-44eb-9589-744043f3ee4f)
![IMG_20230704_193730](https://github.com/koide3/direct_visual_lidar_calibration/assets/109514194/ed4a6126-3325-41d5-b483-e6578810e4bf)

What command should I type to do it？

**Environment:**
 - OS: [e.g. Ubuntu 20.04]
 - ROS version: [e.g., ROS1 noetic]

**Comment by koide3** [comment]
You need to specify the camera distortion params in addition to the intrinsic params as follows:

```cpp
 rosrun direct_visual_lidar_calibration preprocess -av \
  --camera_model plumb_bob \
  --camera_intrinsic 1452.711762456289,1455.877531619469,1265.25895179213,1045.818593664107 \
  --camera_distortion_coeffs -0.04203564850455424,0.0873170980751213,0.002386381727224478,0.005629700706305988,-0.04251149335870252 \
  /tmp/input_bags /tmp/preprocessed
```

**Comment by koide3** [comment]
Possibly, you forgot the backslash at the end of each line?

**Comment by 774880930** [comment]
I've tried that,but it doen't work
![IMG_20230705_131643](https://github.com/koide3/direct_visual_lidar_calibration/assets/109514194/51ec152a-f9f7-4c8e-ac88-c49be89f70f1)
![IMG_20230705_131531](https://github.com/koide3/direct_visual_lidar_calibration/assets/109514194/57976191-8e62-4f08-9a47-a556651ef2d3)

**Comment by 774880930** [comment]
Oh, Yes, I forgot "/" at the end of each line,I thought it meant "or",this is really my misunderstanding!!
Thanks a lot!!!

**Comment by 774880930** [comment]
One more question, if I want to calibrate a line laser and camera, and the line laser changes different positions through the galvanometer, can this package be applied?

**Comment by koide3** [comment]
If you mean a 2D line laser, this package cannot be applied to it. It requires a 3D range sensor.

**Comment by Chatoyant19** [comment]
> You need to specify the camera distortion params in addition to the intrinsic params as follows:
> 
> ```c++
>  rosrun direct_visual_lidar_calibration preprocess -av \
>   --camera_model plumb_bob \
>   --camera_intrinsic 1452.711762456289,1455.877531619469,1265.25895179213,1045.818593664107 \
>   --camera_distortion_coeffs -0.04203564850455424,0.0873170980751213,0.002386381727224478,0.005629700706305988,-0.04251149335870252 \
>   /tmp/input_bags /tmp/preprocessed
> ```

For the two sets of data you provided, livox and ouster, how do I get their camera intrinsics and _distortion_coeffs. I can't seem to parse this information from '/camera_info', because the version of the topic does not match.

**Comment by G4419** [comment]
@Chatoyant19 you can use plotjuggler to see the data.
