### ISSUE TITLE
Some errors about fmt when catkin_make

### ISSUE THREAD

**Issue by weiyunpei** [koide3/direct_visual_lidar_calibration#26]
**Before opening an issue**
If the issue is about build errors:
- [yes] I have read [installation instructions](https://koide3.github.io/direct_visual_lidar_calibration/installation/)

**Describe the bug**
When I want to catkin_make the repo, I got the error about fmt. I have already linked the libfmt successfully.

**Environment:**
 - OS: [Ubuntu 20.04]
 - ROS version: [ROS1 noetic]

**Additional context**
The terminal shows:
[ 85%] Linking CXX executable /home/bit/Workspace/direct_visual_lidar_calibration/devel/lib/direct_visual_lidar_calibration/preprocess

/usr/bin/ld: /home/bit/Workspace/direct_visual_lidar_calibration/devel/lib/libdirect_visual_lidar_calibration.so: undefined reference to `fmt::v8::detail::throw_format_error(char const*)'

/usr/bin/ld: /home/bit/Workspace/direct_visual_lidar_calibration/devel/lib/libdirect_visual_lidar_calibration.so: undefined reference to `std::locale fmt::v8::detail::locale_ref::get<std::locale>() const'

/usr/bin/ld: /home/bit/Workspace/direct_visual_lidar_calibration/devel/lib/libdirect_visual_lidar_calibration.so: undefined reference to `fmt::v8::detail::error_handler::on_error(char const*)'

Could you please tell what should I do to fix the bug?Thanks a lot.

**Comment by james-yoo** [comment]
@weiyunpei 
I had same issue and resolved by:

1. remove libfmt-dev (sudo apt remove libfmt-dev)
2. source build fmt (version: 8.1.1)
3. colcon build
