### ISSUE TITLE
`dst_path` param is repeated in the `positional_option_description`

### ISSUE THREAD

**Issue by SunZezhou** [koide3/direct_visual_lidar_calibration#31]
**Before opening an issue**
If the issue is about build errors:
- [x] I have read [installation instructions](https://koide3.github.io/direct_visual_lidar_calibration/installation/)
- [ ] I have considered using [docker](https://koide3.github.io/direct_visual_lidar_calibration/docker/)

If the issue is about calibration procedure and results:
- [x] I have read [data collection instructions](https://koide3.github.io/direct_visual_lidar_calibration/collection/)
- [x] I have confirmed [the program works on example data](https://koide3.github.io/direct_visual_lidar_calibration/example/)

If the issue is about the algorithm:
- [x] I have read [the paper](https://staff.aist.go.jp/k.koide/assets/pdf/icra2023.pdf)

**Describe the bug**

Thank you for your amazing work, I noticed a very small bug when I was modifying it.

[`p.add("dst_path", 2);`](https://github.com/koide3/direct_visual_lidar_calibration/blob/ca2630ec3edd7112370e8db218fe30c2b16a6cf3/src/vlcal/preprocess/preprocess.cpp#L65C6-L65C6) seems like it should be changed to `p.add("dst_path", 1);`. 

Otherwise it will add `dst_path` twice.  At this point, when I add other command line param, an error maybe reported: 

terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::multiple_occurrences>'
  what():  option '--dst_path' cannot be specified more than once"

**To Reproduce**

`p.add("dst_path", 2);' :

![add2](https://github.com/koide3/direct_visual_lidar_calibration/assets/49157013/6e70e740-d998-40b9-b427-e0a8892edf2d)

`p.add("dst_path", 1);' :

![add1](https://github.com/koide3/direct_visual_lidar_calibration/assets/49157013/57943eba-ef77-4549-aff4-4bafc44dc2a6)

**Expected behavior**

**Screenshots and sample data**
If applicable, add screenshots and sample data to reproduce your problem.

**Environment:**
 - OS: [e.g. Ubuntu 20.04]
 - ROS version: [e.g., ROS1 noetic]

**Additional context**

**Comment by koide3** [comment]
Ah, thanks for reporting the issue. I'll fix it soon.
