### ISSUE TITLE
ROS1 commands to run the project

### ISSUE THREAD

**Issue by teecha** [koide3/direct_visual_lidar_calibration#34]
I have installed the repo based on the guidelines provided in 
https://koide3.github.io/direct_visual_lidar_calibration/

I have collected the rosbag data and when I try to run my data. All I see is the ros2 commands.

It would be really helpful to include the **ros1 commands in the documentation.**

I tried installing ros2 along with ros1 but I was facing issues with sourcing and building the project. So I request for the ros1 commands.

**Comment by koide3** [comment]
Basically, the ROS1 and ROS2 programs have the same arguments and you can just replace `ros2 run` with `rosrun`. You can also ROS1 example commands (with docker) at the bottom of [this page](https://koide3.github.io/direct_visual_lidar_calibration/docker/).
