### ISSUE TITLE
About data collection

### ISSUE THREAD

**Issue by JiSuanJiDaWang** [koide3/direct_visual_lidar_calibration#35]
Hi, thanks for sharing such wonderful works. I am curious about whether it is necessary to move the lidar up and down during collection. I mean if it has been equipped on the robot or vehicle. in which it can only move forward, backward, or spin. will it be useful under the condition? Thanks.

**Comment by koide3** [comment]
Because we need a dense point cloud for calibration, up-down movement is ideal since it fills the gaps of LiDAR scanning lines. Meanwhile, I think forward-backward movement would also help (to some level).

**Comment by JiSuanJiDaWang** [comment]
Got it, Thanks!
