### ISSUE TITLE
How should I run this program when my pic and pointcloud were not in a same rosbag

### ISSUE THREAD

**Issue by FengYuQ** [koide3/direct_visual_lidar_calibration#39]
hi，this is a great work，i would like to run it in my computer，but my data was splited into PCD files and PNG files.So how can i make it work with my data.Thanks for your answer.

**Comment by koide3** [comment]
To feed your own data to the calibration program, you need to create a "preprocessed" data directory that contains LiDAR point clouds, camera images, and a meta data file. The following example and `preprocess_map.cpp` would be a help to understand what data you need to prepare.

https://koide3.github.io/direct_visual_lidar_calibration/example_map/
https://github.com/koide3/direct_visual_lidar_calibration/blob/main/src/preprocess_map.cpp
