### ISSUE TITLE
Hello, I am using velodyne16, but after data preprocessing, the point cloud becomes disorganized

### ISSUE THREAD

**Issue by af-doom** [koide3/direct_visual_lidar_calibration#5]
![2023-04-13 10-53-58 的屏幕截图](https://user-images.githubusercontent.com/91470350/231636353-1c91fbbd-b893-4b7a-9486-657871f3d5bb.png)

**Comment by koide3** [comment]
Please fill the template form when opening an issue to help us your situation and problem.
