### ISSUE TITLE
Hello, I am using velodyne16, but after data preprocessing, the point cloud becomes disorganized

### ISSUE THREAD

**Issue by af-doom** [koide3/direct_visual_lidar_calibration#6]
**Before opening an issue**
If the issue is about build errors:
- [ ] I have read [installation instructions](https://koide3.github.io/direct_visual_lidar_calibration/installation/)
- [1] I have considered using [docker](https://koide3.github.io/direct_visual_lidar_calibration/docker/)

If the issue is about calibration procedure and results:
- [1 ] I have read [data collection instructions](https://koide3.github.io/direct_visual_lidar_calibration/collection/)
- [ ] I have confirmed [the program works on example data](https://koide3.github.io/direct_visual_lidar_calibration/example/)

If the issue is about the algorithm:
- [] I have read [the paper](https://staff.aist.go.jp/k.koide/assets/pdf/icra2023.pdf)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and sample data**
If applicable, add screenshots and sample data to reproduce your problem.

**Environment:**
 - OS: [e.g. Ubuntu 20.04]
 - ROS version: [e.g., ROS1 noetic]

**Additional context**
![2023-04-13 10-53-58 的屏幕截图](https://user-images.githubusercontent.com/91470350/231641977-be96795c-c6fc-4bc6-a3c4-61a301a7e55f.png)

**Comment by koide3** [comment]
Please properly fill the items in the template and describe the problem in detail. It is difficult to find and fix the cause of the problem without sufficient information.

**Comment by Ning030** [comment]
Have you solved this problem? If so, can you provide a solution? Thanks Thanks!

**Comment by koide3** [comment]
Duplicated https://github.com/koide3/direct_visual_lidar_calibration/issues/13
