### ISSUE TITLE
error while running direct_visual_lidar_calibration preprocess

### ISSUE THREAD

**Issue by gitissues79** [koide3/direct_visual_lidar_calibration#7]
- [✓] I have read [installation instructions](https://koide3.github.io/direct_visual_lidar_calibration/installation/)
- [ ✗] I have considered using [docker](https://koide3.github.io/direct_visual_lidar_calibration/docker/)

If the issue is about calibration procedure and results:
- [✓] I have read [data collection instructions](https://koide3.github.io/direct_visual_lidar_calibration/collection/)
- [ ] I have confirmed [the program works on example data](https://koide3.github.io/direct_visual_lidar_calibration/example/)

Environment: 
OS: ubuntu 20.04
ROS Version: noetic

I am having an issue while running preprocess command 
rosrun direct_visual_lidar_calibration preprocess data/ process/ -a -d -v

Error: 

data_path: /lidar-cam-calib/data/
dst_path : /lidar-cam-calib/process/
input_bags:
- /lidar-cam-calib/data/_2023-04-13-17-49-57_0.bag
- /lidar-cam-calib/data/_2023-04-13-17-50-27_1.bag
- /lidar-cam-calib/data/_2023-04-13-17-50-57_2.bag
- /lidar-cam-calib/data/_2023-04-13-17-51-28_3.bag
- /lidar-cam-calib/data/_2023-04-13-17-51-57_4.bag
- /lidar-cam-calib/data/_2023-04-13-17-52-27_5.bag
topics:
- camera_info: /lidar-cam-calib/data/_2023-04-13-17-52-27_5.bag
topics:
- image      :cam0/image_raw
- points     :/vlp16_1/velodyne_points
intensity_channel: intensity
terminate called after throwing an instance of 'rosbag::BagIOException'
  what():  Error opening file: cam0/image_raw
Aborted (core dumped)

**Comment by koide3** [comment]
Please fill the template form when opening an issue to help us recognize your situation and problem.

**Comment by gitissues79** [comment]
I have filled the template and updated the issue i am facing.

**Comment by koide3** [comment]
Thanks for your cooperation. Could you share one of the rosbags so that I can reproduce the problem?

**Comment by gitissues79** [comment]
Can I send it through mail?

**Comment by gitissues79** [comment]
I am sorry, I cant share here.

**Comment by gitissues79** [comment]
the above isuues are resolved and I am able to calibrate it, but I am getting the skewed images and distorted 
the input data/rosbag doesnt have any distortion and skewed images.
![image](https://github.com/koide3/direct_visual_lidar_calibration/assets/130313433/a8f85217-8b84-47e1-a7cd-5d9fdab42b4f)

**Comment by koide3** [comment]
It might be a problem of the viewer (related to OpenGL driver) rather than the undistortion. Did you see any issues in the final calibration results?

**Comment by yahyahajlaoui** [comment]
> The previous issue has been resolved, and I am now able to calibrate it. However, I am encountering skewed and distorted images after preprocessing them. Here is an example image
> 
> ![image](https://user-images.githubusercontent.com/130313433/244594051-6fe1a5b1-48dc-4666-9201-dded4a0efefe.png)
> 
> It is worth noting that the input data from the rosbag does not exhibit any distortion or skewing. When choosing the corresponding points for the initial guess, I am provided with a regular(standard), undistorted image. Here is an example:
> 
> ![image](https://user-images.githubusercontent.com/130313433/244594366-7564a0ae-5f9d-44d5-90af-5f186247de81.png)

Hello, can you please help me how do you solve the issue, I am facing the same. Thank you

**Comment by Giannis-Alamanos** [comment]
How did you solve the issue?

**Comment by pengpengfei97** [comment]
> * [✓] I have read [installation instructions](https://koide3.github.io/direct_visual_lidar_calibration/installation/)
> * [ ✗] I have considered using [docker](https://koide3.github.io/direct_visual_lidar_calibration/docker/)
> 
> If the issue is about calibration procedure and results:
> 
> * [✓] I have read [data collection instructions](https://koide3.github.io/direct_visual_lidar_calibration/collection/)
> * [ ]  I have confirmed [the program works on example data](https://koide3.github.io/direct_visual_lidar_calibration/example/)
> 
> Environment: OS: ubuntu 20.04 ROS Version: noetic
> 
> I am having an issue while running preprocess command rosrun direct_visual_lidar_calibration preprocess data/ process/ -a -d -v
> 
> Error:
> 
> data_path: /lidar-cam-calib/data/ dst_path : /lidar-cam-calib/process/ input_bags:
> 
> * /lidar-cam-calib/data/_2023-04-13-17-49-57_0.bag
> * /lidar-cam-calib/data/_2023-04-13-17-50-27_1.bag
> * /lidar-cam-calib/data/_2023-04-13-17-50-57_2.bag
> * /lidar-cam-calib/data/_2023-04-13-17-51-28_3.bag
> * /lidar-cam-calib/data/_2023-04-13-17-51-57_4.bag
> * /lidar-cam-calib/data/_2023-04-13-17-52-27_5.bag
>   topics:
> * camera_info: /lidar-cam-calib/data/_2023-04-13-17-52-27_5.bag
>   topics:
> * image      :cam0/image_raw
> * points     :/vlp16_1/velodyne_points
>   intensity_channel: intensity
>   terminate called after throwing an instance of 'rosbag::BagIOException'
>   what():  Error opening file: cam0/image_raw
>   Aborted (core dumped)

Hi, friend. I meet the same issue: `Error opening file: /image`. I read the codes and found it perhaps caused by the function https://github.com/koide3/direct_visual_lidar_calibration/blob/82df9955c2bf43a478690d45f9283493ca01343d/src/preprocess_ros1.cpp#L98C110-L98C110 when passing parameters. This function read the `image_topic` as `bag_filename` and can't get the parameter `image_topic` correctly. But I have no idea how to fix the problem, cloud you please help me how you solved this problem? Thanks!
