### ISSUE TITLE
colcon build fail

### ISSUE THREAD

**Issue by Davabbb** [koide3/direct_visual_lidar_calibration#87]
I did everything according to the instructions

colcon build:
29: error: ‘shared_ptr’ in namespace ‘boost’ does not name a template type
   23 |   using shared_ptr = boost::shared_ptr<IntegratedCT_ICPFactor_<TargetFrame, SourceFrame>>;

it takes the boost code from /usr/include/

 - OS: 22.04
 - ROS version: ros2 humble

**Comment by soham2560** [comment]
@Davabbb getting the same error, how did you resolve this?

**Comment by Davabbb** [comment]
@soham2560 It's been so long that I've already forgotten I hope you will succeed good luck
