### ISSUE TITLE
Error glfw

### ISSUE THREAD

**Issue by Davabbb** [koide3/direct_visual_lidar_calibration#88]
glfw error 65544: X11: Failed to open display :2
failed to initialize GLFW

i try xhost local:root and export DISPLAY=:...

**Comment by Davabbb** [comment]
@Seekerzero

**Comment by Seekerzero** [comment]
Are you running this in a virtual machine? Currently glfw needs a physical graphic card to initialize.

**Comment by Davabbb** [comment]
no

**Comment by koide3** [comment]
Can you run `glxinfo`? If not there should be X-related issues that may be unrelated to the calibration program.

**Comment by Davabbb** [comment]
![Снимок экрана от 2024-06-26 11-35-11](https://github.com/koide3/direct_visual_lidar_calibration/assets/57668741/53e4b9e4-62fb-4453-b4be-f6f5ff80f48e)

**Comment by Davabbb** [comment]
![Снимок экрана от 2024-06-26 11-43-22](https://github.com/koide3/direct_visual_lidar_calibration/assets/57668741/8a839993-f599-4539-92cd-135b6958ddbb)

**Comment by Davabbb** [comment]
![image](https://github.com/koide3/direct_visual_lidar_calibration/assets/57668741/80dc39a9-1c7d-4999-b59f-34de96bcff42
)
